### ISSUE TITLE
Getting extra samples of Spool Files

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/edu-benefits-team#10]
Ask Shay for more samples of spool files. The file will have PII in them, but Josh or Jeff can receive. 
If sent preprod files, this is test data and would be able to upload in Preprod.

**Comment by J-Quag** [comment]
An additional example has been provided by Shay... do we need more?

**Comment by akainic** [comment]
@J-Quag Yes, I think we want at least 5 samples so we can really understand as many potential edge cases as possible.
